### ISSUE TITLE
Specification of the desired tokenizer behavior

### ISSUE THREAD

**Issue by wolfgarbe** [quickwit-oss/search-benchmark-game#38]
Could you please specify the desired behavior of the tokenizer to exactly replicate the term/result numbers for the benchmark?
I'm trying to make Seekstorm compatible with your benchmark, but so far I have been unable to replicate the exact term counts (e.g. for the term **"the"**).

I have changed my tokenizer to pure white space tokenizing, non-alphanumeric char trimming (remove all non-letter, non-digit chars from both sides of the term), and lower-casing.
Stemming, apostrophe tokenizing/stemming, domain name tokenizing, hyphen tokenizing, umlaut/accent char folding, CJK-word segmentation, CJK full/halvewidth char folding, CJK traditional/simplified char folding have all been disabled.
I even counted the terms before indexing, to exclude any possible differences during indexing and query.

The differences are in the permille range, but in your published results (https://tantivy-search.github.io/bench/  , collection type count) Tantivy, Lucene, Pisa, Bleeve, Rucene all return exact **4,168,066 docs** for the term **"the"**. In my own test for Lucene with StandardAnalyzer (no stopwords, after commit, forceMerge and restarting Lucene) I get **4.167.903  docs** for the term **"the"**. And in Seekstorm I get **4.167.776 docs** for the term **"the"**.

Any suggestion would be much appreciated.

**Comment by fulmicoton** [comment]
The corpus has been modified to be pre-tokenized no make it easy for engine to reach the same results.

> In my own test for Lucene with StandardAnalyzer (no stopwords, after commit, forceMerge and restarting Lucene)

The code of the benchmark is shared. Do you mean you ran the lucene engine shared in the project, or was it your own code?

**Comment by fulmicoton** [comment]
I don't think we can help you much here, apart from cheering for your success!

**Comment by wolfgarbe** [comment]
Thank you for the explanation. My fault, I thought the normalization between search engines would be through tokenizer specification, but pre-tokenizing in the external corpus transformation makes more sense. I missed that step.
