### ISSUE TITLE
What's the License for this repo?

### ISSUE THREAD

**Issue by Tony-X** [quickwit-oss/search-benchmark-game#43]
Context: I want to compare some workload between Lucene and Tantivy. And I would love to use and contribute this repo. 

I don't currently see a license for this repo and I wish it could be something that is open such as MIT (just like most of the repos under quickwit-oss)

**Comment by fulmicoton** [comment]
Excellent question.. I am ok to slap an MIT license over my commits but the original crate is `jason-wolfe/search-index-benchmark-game`. Let me see if Jason can add a license on the original project.

**Comment by fulmicoton** [comment]
It is not under MIT license.

**Comment by Tony-X** [comment]
> It is not under MIT license.

I guess you meant "it is now under MIT license"? Since I found Jason just added  MIT license to the original repo https://github.com/jason-wolfe/search-index-benchmark-game

**Comment by fulmicoton** [comment]
yes I meant MIT license. I asked Jason to slap a license and rebase our repo over it.
